### ISSUE TITLE
undefined symbol: convertSwigSimpleITKImage

### ISSUE THREAD

**Issue by Celli119** [zarquon42b/RcppSimpleITK#1]
When building the package, on ubuntu 16.04 & 17.10, using the last release of SimpleITK, I always get the following error when linking:
`undefined symbol: convertSwigSimpleITKImage`
Actually, I don't see where the method convertSwigSimpleITKImage is defined. Could you give me hand with this?

**Comment by zarquon42b** [comment]
Hi Francois,
you need to use the R-wrappers from here: https://github.com/zarquon42b/SimpleITK/tree/R-C++-Wrapping/Wrapping/R

**Comment by Celli119** [comment]
It works like a charm, thanks!
